services:
  mongo:
    image: mongo:8.0
    container_name: payment-mongo
    environment:
      MONGO_INITDB_DATABASE: ${PAYMENT_SERVICE_DB_NAME}
    ports: [ "27017:27017" ]
    volumes: [ payment_mongo_data:/data/db ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:${KAFKA_CONTROLLER_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT},CONTROLLER://0.0.0.0:${KAFKA_CONTROLLER_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes: [ kafka_data:/var/lib/kafka/data ]
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:${KAFKA_PORT} --list >/dev/null 2>&1 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports: [ "8084:8080" ]
    depends_on:
      kafka: { condition: service_healthy }

  postgres-user:
    image: postgres:15-alpine
    container_name: postgres-user
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB_NAME}
      POSTGRES_USER: ${USER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
    ports: ["5436:5432"]
    volumes: [user_pg_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_SERVICE_DB_USER} -d ${USER_SERVICE_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-order:
    image: postgres:15-alpine
    container_name: postgres-order
    environment:
      POSTGRES_DB: ${ORDER_SERVICE_DB_NAME}
      POSTGRES_USER: ${ORDER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
    ports: ["5438:5432"]
    volumes: [order_pg_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORDER_SERVICE_DB_USER} -d ${ORDER_SERVICE_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-user:
    image: redis:7-alpine
    container_name: redis-user
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-keycloak:
    image: postgres:15-alpine
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports: ["5437:5432"]
    volumes: [kc_pg_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USER} -d ${KEYCLOAK_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
    ports: ["${KEYCLOAK_SERVER_PORT}:8080"]
    depends_on:
      postgres-keycloak: {condition: service_healthy}
    healthcheck:
      test: ["CMD-SHELL", "exec bash -c 'exec 3<>/dev/tcp/127.0.0.1/9000; echo -e \"GET /health/ready HTTP/1.0\\r\\nHost: localhost\\r\\n\\r\\n\" >&3; grep -q 200 <&3'"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s

  payment-service:
    build: {context: ., dockerfile: payment-service/Dockerfile}
    container_name: payment-service
    environment:
      SERVER_PORT: ${PAYMENT_SERVICE_SERVER_PORT}
      DB_HOST: ${PAYMENT_SERVICE_DB_HOST}
      DB_PORT: ${PAYMENT_SERVICE_DB_PORT}
      DB_NAME: ${PAYMENT_SERVICE_DB_NAME}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      INTERNAL_SERVICE_SECRET: ${INTERNAL_SERVICE_SECRET}
      RANDOM_API_URL: ${RANDOM_API_URL}
    depends_on:
      mongo: { condition: service_healthy}
      kafka: {condition: service_healthy}

  auth-service:
    build: {context: ., dockerfile: auth-service/Dockerfile}
    container_name: auth-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: ${AUTH_SERVICE_SERVER_PORT}
      HTTP_CONNECT_TIMEOUT: ${AUTH_HTTP_CONNECT_TIMEOUT}
      HTTP_READ_TIMEOUT: ${AUTH_HTTP_READ_TIMEOUT}
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ADMIN_REALM: ${KEYCLOAK_ADMIN_REALM}
      KEYCLOAK_ADMIN_CLIENT_ID: ${KEYCLOAK_ADMIN_CLIENT_ID}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}
      APP_ADMIN_USERNAME: ${APP_ADMIN_USERNAME}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      USER_SERVICE_URL: http://user-service:${USER_SERVICE_SERVER_PORT}
      INTERNAL_SERVICE_SECRET: ${INTERNAL_SERVICE_SECRET}
    ports: ["${AUTH_SERVICE_SERVER_PORT}:${AUTH_SERVICE_SERVER_PORT}"]
    depends_on:
      keycloak: {condition: service_healthy}

  user-service:
    build: {context: ., dockerfile: user-service/Dockerfile}
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: ${USER_SERVICE_SERVER_PORT}
      DB_HOST: ${USER_SERVICE_DB_HOST}
      DB_PORT: ${USER_SERVICE_DB_PORT}
      DB_NAME: ${USER_SERVICE_DB_NAME}
      DB_USER: ${USER_SERVICE_DB_USER}
      DB_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      REDIS_HOST: ${USER_SERVICE_REDIS_HOST}
      REDIS_PORT: ${USER_SERVICE_REDIS_PORT}
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/${KEYCLOAK_REALM}
      INTERNAL_SERVICE_SECRET: ${INTERNAL_SERVICE_SECRET}
    ports: ["${USER_SERVICE_SERVER_PORT}:${USER_SERVICE_SERVER_PORT}"]
    depends_on:
      postgres-user: {condition: service_healthy}
      redis-user: {condition: service_healthy}

  gateway-service:
    build: { context: ., dockerfile: gateway-service/Dockerfile }
    container_name: gateway-service
    environment:
      SERVER_PORT: ${GATEWAY_SERVER_PORT}
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/${KEYCLOAK_REALM}
      AUTH_SERVICE_URL: http://auth-service:${AUTH_SERVICE_SERVER_PORT}
      USER_SERVICE_URL: http://user-service:${USER_SERVICE_SERVER_PORT}
      ORDER_SERVICE_URL: http://order-service:${ORDER_SERVICE_SERVER_PORT}
      PAYMENT_SERVICE_URL: http://payment-service:${PAYMENT_SERVICE_SERVER_PORT}
      REDIS_HOST: redis-user
      REDIS_PORT: 6379
    ports: [ "${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}" ]
    depends_on:
      auth-service: { condition: service_started }
      user-service: { condition: service_started }
      order-service: { condition: service_started }
      redis-user: { condition: service_healthy }


  order-service:
    build: {context: ., dockerfile: order-service/Dockerfile}
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: ${ORDER_SERVICE_SERVER_PORT}
      DB_HOST: ${ORDER_SERVICE_DB_HOST}
      DB_PORT: ${ORDER_SERVICE_DB_PORT}
      DB_NAME: ${ORDER_SERVICE_DB_NAME}
      DB_USER: ${ORDER_SERVICE_DB_USER}
      DB_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      PAYMENT_EVENTS_TOPIC: ${PAYMENT_EVENTS_TOPIC}
      INTERNAL_SERVICE_SECRET: ${INTERNAL_SERVICE_SECRET}
    ports: ["${ORDER_SERVICE_SERVER_PORT}:${ORDER_SERVICE_SERVER_PORT}"]
    depends_on:
      postgres-order: {condition: service_healthy}

volumes:
  user_pg_data:
  order_pg_data:
  kc_pg_data:
  payment_mongo_data:
  kafka_data: