apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  USER_SERVICE_DB_HOST: "postgres-user"
  USER_SERVICE_DB_PORT: "5432"
  USER_SERVICE_DB_NAME: "user_db"
  USER_SERVICE_REDIS_HOST: "redis-user"
  USER_SERVICE_REDIS_PORT: "6379"

  ORDER_SERVICE_DB_HOST: "postgres-order"
  ORDER_SERVICE_DB_PORT: "5432"
  ORDER_SERVICE_DB_NAME: "order_db"

  PAYMENT_SERVICE_DB_HOST: "payment-mongo"
  PAYMENT_SERVICE_DB_PORT: "27017"
  PAYMENT_SERVICE_DB_NAME: "payment-db"
  PAYMENT_EVENTS_TOPIC: "payment-events"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  KEYCLOAK_DB_NAME: "keycloak_db"
  KEYCLOAK_REALM: "microservices-realm"
  KEYCLOAK_CLIENT_ID: "app-client"
  KEYCLOAK_ADMIN_REALM: "master"
  KEYCLOAK_ADMIN_CLIENT_ID: "admin-cli"

  APP_ADMIN_USERNAME: "admin"
  JWT_ACCESS_TOKEN_VALIDITY: "900"
  JWT_REFRESH_TOKEN_VALIDITY: "604800"
  RANDOM_API_URL: "https://www.random.org/integers/?num=1&min=1&max=1000&col=1&base=10&format=plain&rnd=new"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
stringData:
  USER_SERVICE_DB_USER: "user_user"
  ORDER_SERVICE_DB_USER: "order_user"
  KEYCLOAK_DB_USER: "kc_user"
  KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME: "kcadmin"

  USER_SERVICE_DB_PASSWORD: "changeme_user"
  ORDER_SERVICE_DB_PASSWORD: "changeme_order"
  KEYCLOAK_DB_PASSWORD: "changeme_kc"
  KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD: "changeme_kc_admin"
  KEYCLOAK_CLIENT_SECRET: "changeme_client"
  APP_ADMIN_PASSWORD: "changeme_app_admin"
  INTERNAL_SERVICE_SECRET: "changeme_internal"