server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/microservices-realm}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/auth/**
            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/orders/**
            - id: user-service
              uri: ${USER_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/api/users/**,/api/cards/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

