spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/microservices-realm}
  app:
    internal-secret: ${INTERNAL_SERVICE_SECRET:dev-internal-secret}
  application:
    name: user-service
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:userdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cache:
    type: redis

app:
  cache:
    ttl-minutes: 10
  internal-secret: ${INTERNAL_SERVICE_SECRET:dev-internal-secret}

server:
  port: 8080